[project]
name = "midianalytis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mido>=1.3.3",
    "music21>=9.5.0",
    "pandas>=2.2.3",
    "pretty-midi>=0.2.10",
]
